### ISSUE TITLE
Problems installing through opam

### ISSUE THREAD

**Issue by Russsgithub** [savonet/ocaml-lilv#3]
If i run ``` opam install lilv ``` I get ```no package named lilv found.```

If i use the git code to pin using opam I get a ``` dependency couldn't be met - lilv -> conf-lilv```

Thanks

**Comment by smimram** [comment]
Apparently [some more work is needed on the opam package](https://github.com/ocaml/opam-repository/pull/18436).

@toots what it missing from your PR?

**Comment by toots** [comment]
I forgot.. 😅 Just cleaned it a bit, I'll push it for review shortly.
